### PR TITLE
feature/ROT981-230 Add configurable structured logging

### PR DESCRIPTION
**Pull request by ChalkyT**

### CODE REVIEW

**Review by joel-wright — DISMISSED** [review]

**Comment by joel-wright** [comment]
@jtiddDI is looking into the title parsing issue

**Comment by joel-wright** [comment]
In `.github/workflows/validate-pr-title.yml` you need to update skimit/validate-pull-request-title-github-action@v1.1.0` to `skimit/validate-pull-request-title-github-action@v1.1.2`, then everything will be fine & I can still review

**Review by joel-wright — APPROVED** [review]
Looks good :)

**Comment by joao-costa-di** [comment]
Hey @joel-wright @ChalkyT! Sorry to resurrect a closed PR, but we came across some questions about using the `di-logging` logger on floating point, particularly regarding serialisation.

We're going to have serialised logs on our FP production environment so they play well with grafana, and so we're going to set `ENVIRONMENT=prod`.

However, one thing we noted is that the default behaviour for the logger is the dev environment behaviour, i.e., not serialise logs. Could this perhaps be reversed? That way if we forget to set `ENVIRONMENT` it defaults to the production behaviour, making it so that the onus is on the dev environment to report itself as such.

What do you think?
CC: @psi77

**Pull request merged**
